import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Providers from "@/providers/Providers";
import Sidebar from "@/components/Dashboard/ui/Sidebar";
import Topbar from "@/components/Dashboard/ui/Topbar";

const poppins = Poppins({
  variable: "--poppins-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} ${poppins.variable} antialiased `}>
        <Providers>
          <main className="flex flex-row w-full bg-[#fdfdfd] min-h-screen">
            <Sidebar />
            <section className="flex flex-col w-full p-4 ml-12 lg:ml-64">
              <Topbar />
              {children}
            </section>
          </main>
        </Providers>
      </body>
    </html>
  );
}
